### ISSUE TITLE
Some suggestions for bitaac

### ISSUE THREAD

**Issue by Taarek** [bitaac/bitaac#3]
One thing I would like is when you register a account. It will log your IP automatically but it shouldnt be stored as clear ip example: 127.0.0.1 it should be stored as ip2long

This is 127.0.0.1 in ip2long: 2130706433. This could be really useful against people who is banned from playing or good way to blacklist people from the official OTLand blacklist thread.

Another suggestion is Equipment box where it shows your equipment and which country a certain player is from. And all should be handled from the IP Address.

**Comment by Fluppix** [comment]
Not sure if that is the right way, a lot of players do use Proxies to connect to the server.

**Comment by Taarek** [comment]
@Fluppix Yes maybe, but how high is the chances that people use a proxy upon registeration? 

Or did I understand your post wrong? xD

**Comment by Fluppix** [comment]
Well the chance is pretty high, once you connect with a proxy you will stay with it until you disconnect the connection by yourself.
I would say 25% of proxy users would have their proxy enabled while registration (or any other internet activity)

**Comment by Raggaer** [comment]
I would say that saving the users ip is kinda useless as @Fluppix said
